# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('comuna_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comuna_nombre', models.CharField(max_length=64)),
                ('provincia_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('provincia_id', models.IntegerField(primary_key=True, serialize=False)),
                ('provincia_nombre', models.CharField(max_length=64)),
                ('region_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_nombre', models.CharField(max_length=64)),
                ('region_ordinal', models.CharField(max_length=4)),
            ],
        ),
    ]
